name: Create and upload artifact

on:
  push:
    branches:
      - master

jobs:
  Terraform:
    name: Create and upload artifact
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Create artifact
      run: rm -rf artifact ; mkdir -p artifact && cd artifact && tar -czvf artifact.tgz ..

    - name: Upload artifact
      run: |
        ls artifact | while read file; do aws s3 cp $file s3://test-artifacts; done
      env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
